import { Link, useNavigate, useParams } from "react-router-dom";
import { useMemo, useState } from "react";
import logo from "../../assets/logo/cypheris-logo.jpg";
import "./PublicPages.css";

const areas = {
  command: { title: "Security Command", kicker: "SENTINEL COMMAND", text: "A single operating surface for security posture, active findings, assets, investigations and response state.", bullets: ["Executive security posture", "Prioritized alerts and investigations", "Asset and identity visibility", "Response ownership and status"] },
  context: { title: "Context Fabric", kicker: "CONNECTED SECURITY CONTEXT", text: "Cypheris connects observations into relationships so analysts can understand what an event touches, who is involved and why it matters.", bullets: ["Asset relationships", "Identity and access context", "Telemetry correlation", "Evidence-backed explanations"] },
  risk: { title: "Risk Graph", kicker: "RELATIONSHIP-AWARE RISK", text: "Move beyond isolated findings. Risk Graph shows how assets, identities, exposures and trust relationships combine into meaningful security risk.", bullets: ["Risk relationships", "Choke-point discovery", "Prioritized exposure", "Investigation pivots"] },
  investigations: { title: "Investigations", kicker: "SECURITY CASEWORK", text: "Turn a detection into a defensible investigation with evidence, timeline, entities, ownership and response state in one place.", bullets: ["Investigation workspace", "Evidence collection", "Timeline correlation", "Ownership and status"] },
  identity: { title: "Identity Center", kicker: "IDENTITY CONTEXT", text: "Understand the people, service identities and access relationships connected to the security picture.", bullets: ["Identity inventory", "Access context", "Related assets", "Investigation pivots"] },
  drift: { title: "Security Drift", kicker: "CHANGE INTELLIGENCE", text: "See what changed, when it changed and which security relationships may have been affected.", bullets: ["Change timeline", "Configuration observations", "Affected assets", "Drift investigation"] },
  timeline: { title: "Security Timeline", kicker: "CHRONOLOGICAL CONTEXT", text: "Bring events, changes, findings and investigation activity into one chronological security view.", bullets: ["Event chronology", "Cross-entity pivots", "Investigation markers", "Evidence references"] },
  evidence: { title: "Evidence Fabric", kicker: "DEFENSIBLE SECURITY", text: "Keep the records behind a security conclusion connected to the investigation that used them.", bullets: ["Evidence records", "Source attribution", "Investigation links", "Audit-friendly context"] },
  lyromi: { title: "LYROMI Intelligence", kicker: "CONTEXTUAL SECURITY AI", text: "LYROMI is designed to reason over the security context Cypheris actually has access to and clearly distinguish evidence from uncertainty.", bullets: ["Workspace-grounded answers", "Investigation summaries", "Security context explanation", "No invented telemetry"] },
  integrations: { title: "Integrations", kicker: "CONNECT YOUR ENVIRONMENT", text: "Bring authorized telemetry into Cypheris through infrastructure sensors, cloud connections and security data integrations.", bullets: ["Docker deployment", "Kubernetes deployment", "AWS and cloud onboarding", "Security API connections"] },
  reports: { title: "Reports", kicker: "SECURITY COMMUNICATION", text: "Turn operational security context into reports that can be reviewed by technical teams and leadership.", bullets: ["Security posture summaries", "Investigation reporting", "Risk reporting", "Export-ready views"] },
  api: { title: "Developer API", kicker: "PROGRAMMABLE SECURITY", text: "Build on the Cypheris security fabric with authenticated APIs for integrations, automation and internal tooling.", bullets: ["Authenticated API surface", "Integration workflows", "Automation-ready architecture", "Developer documentation"] },
};

function PublicNav() {
  return <header className="public-nav"><Link to="/" className="public-brand"><img src={logo} alt="Cypheris" /><span><b>CY​​PHERIS</b><small>DECODE YOUR SECURITY</small></span></Link><nav><Link to="/platform">Platform</Link><Link to="/demo">Interactive demo</Link><Link to="/about">Company</Link></nav><div className="public-actions"><Link to="/login" className="public-signin">Sign in</Link><Link to="/trial" className="public-primary">Start 14-day trial <b>→</b></Link></div></header>;
}

export function Trial() {
  return <main className="public-page"><PublicNav/><section className="trial-hero"><div><span className="public-kicker">CYPHERIS / 14-DAY EVALUATION</span><h1>Experience the security picture before you connect production infrastructure.</h1><p>Create a workspace, explore the Cypheris security model, and connect your own environment when you're ready. No infrastructure is required to understand the product.</p><div className="public-cta-row"><Link to="/signup?trial=14" className="public-primary big">Start 14-day free trial <b>→</b></Link><Link to="/demo" className="public-secondary big">Explore demo</Link></div><div className="trial-points"><span>14 DAYS</span><span>NO CREDIT CARD</span><span>WORKSPACE-FIRST ONBOARDING</span></div></div><div className="trial-console"><div className="console-label">TRIAL WORKSPACE / READY</div><div className="trial-score"><strong>71</strong><span>SECURITY POSTURE</span></div><div className="trial-stats"><span><b>42</b> Assets</span><span><b>06</b> Critical findings</span><span><b>04</b> Attack paths</span><span><b>17</b> Events</span></div><div className="trial-bar"><i style={{width:"71%"}} /></div><small>Synthetic demo data is clearly labeled. Your connected environment remains separate.</small></div></section><section className="public-section"><div className="public-section-head"><span className="public-kicker">THE EVALUATION PATH</span><h2>Value first. Infrastructure second.</h2></div><div className="steps-grid">{[["01","Create","Create your company workspace and secure administrator account."],["02","Explore","Open a ready-to-understand security environment and learn the workflow."],["03","Investigate","Follow an alert through context, risk, evidence and LYROMI."],["04","Connect","When you're ready, connect Docker, Kubernetes, AWS, cloud or API sources."]].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section></main>;
}

export function Demo() {
  const [active, setActive] = useState("overview");
  const demo = { overview: ["Security posture", "71", "6 critical findings", "42 monitored assets"], alerts: ["Active findings", "06", "2 need immediate investigation", "4 correlated to attack paths"], risk: ["Risk graph", "04", "attack paths identified", "3 high-impact choke points"], lyromi: ["LYROMI", "AI", "Context available", "Ask about the synthetic security environment"] };
  const current = demo[active];
  return <main className="public-page demo-page"><PublicNav/><section className="demo-hero"><span className="public-kicker">INTERACTIVE PRODUCT DEMO / SYNTHETIC ENVIRONMENT</span><h1>Walk through the Cypheris security workflow.</h1><p>Everything below is a controlled demonstration environment. No real customer infrastructure is connected.</p></section><section className="demo-shell"><aside>{Object.keys(demo).map((key)=><button key={key} className={active===key?"active":""} onClick={()=>setActive(key)}>{key === "lyromi" ? "LYROMI Intelligence" : key[0].toUpperCase()+key.slice(1)}<span>→</span></button>)}<Link to="/trial" className="demo-trial">Start a real trial →</Link></aside><div className="demo-workspace"><div className="demo-top"><span>CY​​PHERIS SENTINEL</span><b>DEMO ENVIRONMENT</b></div><div className="demo-main"><div className="demo-card hero-card"><small>{current[0]}</small><strong>{current[1]}</strong><span>{current[2]}</span><p>{current[3]}</p></div><div className="demo-card"><small>CONNECTED CONTEXT</small><div className="fake-graph"><i/><i/><i/><i/><b>CY</b></div><p>Assets, identities, findings and evidence form the relationship layer.</p></div><div className="demo-card wide"><small>INVESTIGATION SIGNAL</small><div className="signal-row"><span>Identity</span><b>→</b><span>Asset</span><b>→</b><span>Finding</span><b>→</b><span>Evidence</span></div><p>Move through the same chain an analyst uses to understand why a finding matters.</p></div></div></div></section></main>;
}

export function About() { return <main className="public-page"><PublicNav/><section className="about-hero"><span className="public-kicker">ABOUT CYPHERIS</span><h1>Built to turn disconnected security signals into a security picture.</h1><p>Cypheris is an independent security platform project focused on connecting telemetry, context, relationships, risk, investigation and AI explanation in one command layer.</p></section><section className="about-grid"><article><span>THE PRODUCT</span><h2>Cypheris Core</h2><p>A network security platform powered by PNSTAP, with Cypheris Sentinel as its operational command surface and LYROMI as its contextual intelligence layer.</p></article><article><span>THE BUILDER</span><h2>Anthony Emmanuella Mmasinachi</h2><p>Founder and independent product builder behind the Cypheris project, responsible for its architecture, engineering, product direction and implementation.</p><small>Cypheris is independently built and developed.</small></article><article><span>THE PRINCIPLE</span><h2>Evidence before certainty.</h2><p>Cypheris should never pretend an environment contains data it does not have. Demo data is explicitly synthetic; connected workspace data is treated as the source of truth.</p></article></section><section className="public-section"><div className="public-section-head"><span className="public-kicker">THE SECURITY FABRIC</span><h2>Telemetry → Context → Relationships → Risk → Investigation → Response → AI explanation.</h2></div><div className="fabric-line">{["Telemetry","Context","Relationships","Risk","Investigation","Response","AI explanation"].map((x,i)=><div key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section></main>; }

export function Platform() { return <main className="public-page"><PublicNav/><section className="platform-hero"><span className="public-kicker">THE CYPHERIS PLATFORM</span><h1>One security fabric. Multiple ways to understand what matters.</h1><p>Explore every major product domain before entering the workspace. Each capability has a focused surface rather than being buried inside one dashboard.</p></section><section className="area-grid">{Object.entries(areas).map(([key,item])=><Link key={key} to={`/platform/${key}`}><span>{item.kicker}</span><h3>{item.title}</h3><p>{item.text}</p><b>Explore capability →</b></Link>)}</section></main>; }

export function ProductDetail() { const { area } = useParams(); const item = areas[area] || areas.command; return <main className="public-page"><PublicNav/><section className="detail-hero"><span className="public-kicker">{item.kicker}</span><h1>{item.title}</h1><p>{item.text}</p><div className="public-cta-row"><Link to="/demo" className="public-primary big">See it in the demo <b>→</b></Link><Link to="/trial" className="public-secondary big">Start 14-day trial</Link></div></section><section className="detail-body"><div className="detail-explain"><span className="public-kicker">WHAT IT DOES</span><h2>Designed as a real product surface, not a placeholder screen.</h2><p>Cypheris separates this capability so teams can understand its purpose, follow the underlying security context and then use it inside the authenticated workspace.</p></div><div className="detail-list">{item.bullets.map((x,i)=><div key={x}><span>0{i+1}</span><strong>{x}</strong><b>→</b></div>)}</div></section></main>; }
