FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY analytics-hub-python/src/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY analytics-hub-python ./analytics-hub-python
WORKDIR /app/analytics-hub-python/src
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
