import { Link } from "react-router-dom";
import logo from "../../assets/logo/cypheris-logo.jpg";
import "./Home.css";

export default function Home() {
  return <div className="home-page">
    <header className="home-nav"><Link to="/" className="home-brand"><img src={logo} alt="Cypheris"/><span><strong>Cypheris</strong><small>Decode Your Security</small></span></Link><nav><a href="#platform">Platform</a><a href="#how">How it works</a></nav><div className="home-actions"><Link to="/login" className="home-login">Sign in</Link></div></header>
    <main>
      <section className="home-hero"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><i/> SECURITY INTELLIGENCE PLATFORM</div><h1>See the security story.<br/><span>Understand what changed.</span></h1><p>Cypheris connects security telemetry, infrastructure context and investigations into one security intelligence platform powered by PNSTAP™.</p><div className="hero-actions"><Link to="/login" className="home-cta large">Enter Cypheris <span>→</span></Link></div></div><div className="hero-console" aria-label="Cypheris platform architecture preview"><div className="console-top"><span className="console-dot"/><span>CYPHERIS / SECURITY FABRIC</span><b>CONTEXT</b></div><div className="console-map"><div className="map-ring ring-1"/><div className="map-ring ring-2"/><div className="map-ring ring-3"/><div className="map-node center"><img src={logo} alt=""/><strong>CY</strong><small>WORKSPACE</small></div><div className="map-node node-a"><strong>ASSET</strong><small>inventory</small></div><div className="map-node node-b"><strong>IDENTITY</strong><small>access</small></div><div className="map-node node-c"><strong>TELEMETRY</strong><small>sensor</small></div><div className="map-node node-d"><strong>FINDING</strong><small>evidence</small></div></div><div className="console-bottom"><span>01 Connect</span><span>02 Correlate</span><span>03 Prioritize</span><span>04 Investigate</span></div></div></section>
      <section className="principle-strip"><div><strong>Security signals</strong><span>become connected context</span></div><div><strong>Connected context</strong><span>becomes defensible priority</span></div><div><strong>Defensible priority</strong><span>becomes an investigation</span></div></section>
      <section className="home-section" id="platform"><div className="section-heading"><div><span className="eyebrow">THE CYPHERIS MODEL</span><h2>Not another alert wall.</h2></div><p>Cypheris brings assets, identities, telemetry, alerts, risk, investigations and evidence into one connected security model.</p></div><div className="capability-grid"><article><span>01</span><h3>Connect</h3><p>Bring authorized security telemetry and infrastructure into one workspace.</p></article><article><span>02</span><h3>Context</h3><p>Relate assets, identities, findings and activity instead of treating them as isolated records.</p></article><article><span>03</span><h3>Prioritize</h3><p>Use risk relationships and attack paths to understand what matters.</p></article><article><span>04</span><h3>Investigate</h3><p>Move from detection into evidence, timeline, ownership and response.</p></article><article><span>05</span><h3>Understand</h3><p>Security Drift makes meaningful changes visible across the environment.</p></article><article><span>06</span><h3>Explain</h3><p>LYROMI adds contextual intelligence to the security workspace.</p></article></div></section>
      <section className="home-section dark-section" id="how"><div className="section-heading"><div><span className="eyebrow">FROM SIGNAL TO DECISION</span><h2>One continuous security workflow.</h2></div><p>Telemetry becomes context, context becomes priority, and priority becomes an investigation your team can understand.</p></div><div className="workflow"><div><span>01</span><strong>Collect</strong><p>Authorized sensors and integrations provide observations.</p></div><div><span>02</span><strong>Connect</strong><p>Assets, identities and findings form relationships.</p></div><div><span>03</span><strong>Prioritize</strong><p>Risk context surfaces meaningful relationships.</p></div><div><span>04</span><strong>Investigate</strong><p>Evidence and timeline support the case.</p></div><div><span>05</span><strong>Respond</strong><p>Ownership and status carry the work forward.</p></div></div></section>
      <section className="home-final"><span className="eyebrow">CYPHERIS SECURITY FABRIC</span><h2>Your security command layer.</h2><p>Sign in to your Cypheris workspace to continue.</p><Link to="/login" className="home-cta large">Sign in to Cypheris <span>→</span></Link></section>
    </main><footer className="home-footer"><Link to="/"><img src={logo} alt="Cypheris"/></Link><span>Cypheris · Decode Your Security</span><div><Link to="/login">Sign in</Link></div></footer>
  </div>;
}
