import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { request, Page, Card, Table } from "./PlatformPrimitives";

export function TeamAdmin(){
  const [members,setMembers]=useState([]); const [invitations,setInvitations]=useState([]); const [form,setForm]=useState({email:"",full_name:"",role:"Analyst"}); const [invite,setInvite]=useState(""); const [msg,setMsg]=useState("");
  const load=()=>{request("/api/workspace/team").then(x=>setMembers(x.members||[])).catch(e=>setMsg(e.message));request("/api/workspace/invitations").then(x=>setInvitations(x.invitations||[])).catch(()=>{})};
  useEffect(load,[]);
  const create=async()=>{setMsg("");setInvite("");try{const x=await request("/api/workspace/invitations",{method:"POST",body:JSON.stringify(form)});const token=x.invite_token;setInvite(`${window.location.origin}/invite/${token}`);setMsg("Invitation created. Copy the secure invitation link and send it to the member.");setForm({email:"",full_name:"",role:"Analyst"});load()}catch(e){setMsg(e.message)}};
  return <Page eyebrow="ADMINISTRATION / TEAM" title="Team & access" description="Add members to this organization with explicit roles. Invitations expire after seven days and are scoped to this workspace."><div className="two-column"><Card title="Invite a member" meta="Administrator only"><div className="form-grid"><input placeholder="Full name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/><input type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Analyst</option><option>Viewer</option><option>Admin</option></select><button className="primary-button" onClick={create}>Create invitation</button></div>{msg&&<p className="notice">{msg}</p>}{invite&&<div className="invite-link"><input readOnly value={invite}/><button className="secondary-button" onClick={()=>navigator.clipboard?.writeText(invite)}>Copy link</button></div>}</Card><Card title="Role model"><div className="role-list"><span><b>Admin</b> — workspace, billing, branding and member administration.</span><span><b>Analyst</b> — investigate security data and work assigned cases.</span><span><b>Viewer</b> — read security context, reports and workspace state.</span></div></Card></div><Card title="Active members"><Table columns={["Name","Email","Role","Status","Last login"]} rows={members.map(x=>[x.full_name,x.email,x.role,x.status,x.last_login||"Never"])}/></Card><Card title="Invitation history"><Table columns={["Name","Email","Role","Expires","Accepted"]} rows={invitations.map(x=>[x.full_name,x.email,x.role,x.expires_at,x.accepted_at||"Pending"])}/></Card></Page>
}

export function BrandingAdmin(){
  const [company,setCompany]=useState(null); const [logoUrl,setLogoUrl]=useState(""); const [primary,setPrimary]=useState("#00E5FF"); const [secondary,setSecondary]=useState("#0A1628"); const [msg,setMsg]=useState("");
  useEffect(()=>{request("/api/workspace/company").then(x=>{setCompany(x.company);setLogoUrl(x.company.logo_url||"");setPrimary(x.company.brand_primary_color||"#00E5FF");setSecondary(x.company.brand_secondary_color||"#0A1628")}).catch(e=>setMsg(e.message))},[]);
  const save=async()=>{try{const x=await request("/api/workspace/company/branding",{method:"PUT",body:JSON.stringify({logo_url:logoUrl||null,primary_color:primary,secondary_color:secondary})});setCompany({...company,...x.company});setMsg("Workspace branding saved.")}catch(e){setMsg(e.message)}};
  return <Page eyebrow="ADMINISTRATION / BRAND" title="Workspace identity" description="Business and Enterprise workspaces can carry their own logo and visual colors. Trial workspaces can configure the identity before choosing a paid plan."><div className="two-column"><Card title="Brand controls"><div className="form-grid"><label>Logo URL<input placeholder="https://.../logo.png" value={logoUrl} onChange={e=>setLogoUrl(e.target.value)}/></label><label>Primary color<input type="color" value={primary} onChange={e=>setPrimary(e.target.value)}/></label><label>Secondary color<input type="color" value={secondary} onChange={e=>setSecondary(e.target.value)}/></label><button className="primary-button" onClick={save}>Save identity</button></div>{msg&&<p className="notice">{msg}</p>}</Card><Card title="Preview"><div className="branding-preview"><div className="brand-preview-mark" style={{background:primary}}>{logoUrl?<img src={logoUrl} alt=""/>:"CY"}</div><div><strong>{company?.company_name||"Organization"}</strong><p style={{color:secondary}}>Cypheris workspace</p></div></div></Card></div></Page>
}
