import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
function headers(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
async function get(path){const r=await fetch(`${API}${path}`,{headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}
function Shell({children}){return <div className="platform-shell"><aside className="platform-sidebar"><Link className="platform-brand" to="/workspace"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">INTELLIGENCE</div><nav><Link to="/workspace">Overview</Link><Link to="/workspace/security">Security</Link><Link to="/workspace/risk-graph">Risk Graph</Link><Link to="/workspace/compliance">Compliance</Link><Link to="/workspace/attack-paths">Attack Paths</Link><Link to="/workspace/lyromi">LYROMI</Link></nav></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Context engine</span><Link to="/workspace">Back to command center</Link></header><main className="platform-content">{children}</main></section></div>}
function Card({title,children}){return <section className="data-card"><div className="card-head"><span>{title}</span></div>{children}</section>}
function Tile({to,kicker,title,body}){return <Link className="data-card" to={to}><div className="card-head"><span>{kicker}</span><small>Open →</small></div><h2>{title}</h2><p>{body}</p></Link>}
function RiskBadge({band}){return <span className={`risk-badge risk-${String(band||"low").toLowerCase()}`}>{band||"LOW"}</span>}

export function SecurityHub(){return <Shell><div className="page-heading"><div><span>SECURITY PLATFORM</span><h1>Security intelligence</h1><p>Move from individual findings to context, priority and evidence.</p></div></div><div className="two-column"><Tile to="/workspace/alerts" kicker="01 / DETECTION" title="Alert center" body="Review findings and prioritize what needs attention."/><Tile to="/workspace/risk-graph" kicker="02 / CONTEXT" title="Security Context Graph" body="See the live relationships Cypheris has evidence for across environments, identities, integrations, telemetry and findings."/><Tile to="/workspace/attack-paths" kicker="03 / PRIORITY" title="Attack paths" body="Surface only evidence-backed combinations of open findings and observed network activity."/><Tile to="/workspace/compliance" kicker="04 / GOVERNANCE" title="Compliance center" body="Map evidence to recognizable security control frameworks."/><Tile to="/workspace/intelligence" kicker="05 / INTELLIGENCE" title="Threat intelligence" body="Bring contextual intelligence into the investigation workflow."/><Tile to="/workspace/lyromi" kicker="06 / AI" title="LYROMI" body="Ask the local AI intelligence layer about the security environment."/></div></Shell>}

export function RiskGraph(){const [d,setD]=useState(null);const [err,setErr]=useState("");useEffect(()=>{get("/api/risk/context").then(setD).catch(e=>setErr(e.message))},[]);const s=d?.summary||{};const nodes=d?.nodes||[];const edges=d?.edges||[];return <Shell><div className="page-heading"><div><span>CONTEXT ENGINE</span><h1>Security Context Graph</h1><p>Live relationships assembled from the security evidence available to this workspace.</p></div></div>{err&&<div className="notice">{err}</div>}<div className="metric-grid"><Card title="Graph nodes">{s.nodes??0} entities</Card><Card title="Relationships">{s.relationships??0} observed links</Card><Card title="Findings">{s.alerts??0} alerts</Card><Card title="Connected sources">{s.connected_sources??0} sensors + integrations</Card></div><Card title="Relationship view"><div className="graph-stage"><div className="graph-node center">CYPHERIS<br/><small>SECURITY FABRIC</small></div>{nodes.filter(n=>n.id!=="company").slice(0,12).map((n,i)=><div key={n.id} className={`graph-node n${(i%5)+1}`} title={`${n.type}: ${n.label}`}>{String(n.label).slice(0,24)}<small>{n.type}</small></div>)}{[1,2,3,4,5].map(i=><div key={i} className={`graph-line l${i}`}/>)}</div><div className="graph-legend"><span><i className="legend-dot"/>Environment</span><span><i className="legend-dot"/>Identity</span><span><i className="legend-dot"/>Finding</span><span><i className="legend-dot"/>Network</span></div><p className="notice">{nodes.length ? `${nodes.length} evidence-backed entities and ${edges.length} relationships are available to the graph.` : "No connected security evidence is available yet. Connect a sensor or integration to start building the graph."}</p></Card></Shell>}

const frameworks=[['NIST CSF','Identify · Protect · Detect · Respond · Recover'],['ISO 27001','Information security control readiness'],['SOC 2','Security, availability and evidence readiness'],['PCI DSS','Payment environment security readiness']];
export function Compliance(){return <Shell><div className="page-heading"><div><span>GOVERNANCE</span><h1>Compliance center</h1><p>Map security evidence to recognizable control frameworks and show where the organization needs attention.</p></div></div><div className="pricing-grid">{frameworks.map(([name,desc])=><Card key={name} title={name}><strong>Readiness workspace</strong><p>{desc}</p><div className="progress-track"><span style={{width:'0%'}}/></div><small>Evidence collection begins when connected security data is available.</small></Card>)}</div></Shell>}

export function AttackPaths(){const [d,setD]=useState(null);const [p,setP]=useState(null);const [err,setErr]=useState("");useEffect(()=>{Promise.all([get("/api/risk/attack-paths"),get("/api/risk/priorities")]).then(([paths,priorities])=>{setD(paths);setP(priorities)}).catch(e=>setErr(e.message))},[]);const paths=d?.paths||[];const priorities=p?.items||[];return <Shell><div className="page-heading"><div><span>RISK PRIORITIZATION</span><h1>Attack paths</h1><p>Prioritize connected exposure using severity, reachability and observed telemetry instead of alert volume alone.</p></div></div>{err&&<div className="notice">{err}</div>}<div className="metric-grid"><Card title="Open findings">{p?.total_open_findings??0}</Card><Card title="Observed flows">{p?.telemetry??0}</Card><Card title="Calculated paths">{paths.length}</Card><Card title="Method">Evidence weighted</Card></div>{priorities.length>0&&<Card title="Priority queue"><div className="priority-list">{priorities.slice(0,6).map(item=><div className="priority-row" key={item.id}><div><strong>{item.title}</strong><small>{item.severity} · {item.status}</small></div><RiskBadge band={item.band}/><strong>{item.score}</strong></div>)}</div></Card>}{paths.length?<Card title="Evidence-backed paths"><div className="pricing-grid">{paths.map(path=><div className="data-card nested-card" key={path.id}><div className="card-head"><RiskBadge band={path.band}/><strong>{path.score}/100</strong></div><h2>{path.title}</h2><p>{path.description}</p><div className="path-chain"><span>{path.entry}</span><b>→</b><span>{path.target}</span></div><small>{path.hops} hop{path.hops===1?"":"s"} · Evidence: {path.evidence.join(" + ")}</small></div>)}</div></Card>:<Card title="Path analysis"><div className="empty-state"><div className="empty-orbit">↗</div><strong>{d?.reason||"Calculating from connected evidence…"}</strong><p>Cypheris only surfaces a path when the workspace has enough connected evidence to support the finding.</p><Link className="secondary-button" to="/workspace/integrations">Connect environment</Link></div></Card>}</Shell>}
