import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Overview } from "./WorkspacePages";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
function headers(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
async function get(path){const r=await fetch(`${API}${path}`,{headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}
function Shell({children}){return <div className="platform-shell"><aside className="platform-sidebar"><Link className="platform-brand" to="/workspace"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">INTELLIGENCE</div><nav><Link to="/workspace">Overview</Link><Link className="active" to="/workspace/risk-graph">Risk Graph</Link><Link to="/workspace/compliance">Compliance</Link><Link to="/workspace/attack-paths">Attack Paths</Link><Link to="/workspace/lyromi">LYROMI</Link></nav></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Context engine</span><Link to="/workspace">Back to command center</Link></header><main className="platform-content">{children}</main></section></div>}
function Card({title,children}){return <section className="data-card"><div className="card-head"><span>{title}</span></div>{children}</section>}
export function RiskGraph(){const [d,setD]=useState(null);useEffect(()=>{get("/api/dashboard/").then(setD).catch(()=>{})},[]);const m=d?.metrics||{};return <Shell><div className="page-heading"><div><span>CONTEXT ENGINE</span><h1>Security Context Graph</h1><p>Cypheris is designed to connect signals instead of treating every finding as an isolated alert.</p></div></div><div className="metric-grid"><Card title="Assets">{m.online_sensors??0} active sources</Card><Card title="Signals">{m.telemetry_total??0} observed records</Card><Card title="Alerts">{m.active_alerts??0} active findings</Card><Card title="Integrations">{m.online_integrations??0} online connections</Card></div><Card title="Relationship view"><div className="graph-stage"><div className="graph-node center">CYPHERIS<br/><small>SECURITY FABRIC</small></div><div className="graph-node n1">ENVIRONMENT</div><div className="graph-node n2">IDENTITY</div><div className="graph-node n3">TELEMETRY</div><div className="graph-node n4">ALERT</div><div className="graph-node n5">RESPONSE</div><div className="graph-line l1"/><div className="graph-line l2"/><div className="graph-line l3"/><div className="graph-line l4"/><div className="graph-line l5"/></div><p className="notice">The graph is a product direction as well as a UI surface: the goal is to correlate environment, identity, telemetry, detections and response context before assigning priority.</p></Card></Shell>}

const frameworks=[['NIST CSF','Identify · Protect · Detect · Respond · Recover'],['ISO 27001','Information security control readiness'],['SOC 2','Security, availability and evidence readiness'],['PCI DSS','Payment environment security readiness']];
export function Compliance(){return <Shell><div className="page-heading"><div><span>GOVERNANCE</span><h1>Compliance center</h1><p>Map security evidence to recognizable control frameworks and show where the organization needs attention.</p></div></div><div className="pricing-grid">{frameworks.map(([name,desc])=><Card key={name} title={name}><strong>Readiness workspace</strong><p>{desc}</p><div className="progress-track"><span style={{width:'0%'}}/></div><small>Evidence collection begins when connected security data is available.</small></Card>)}</div></Shell>}

export function AttackPaths(){return <Shell><div className="page-heading"><div><span>RISK PRIORITIZATION</span><h1>Attack paths</h1><p>Prioritize combinations of exposure, identity, asset importance and security findings rather than ranking isolated issues.</p></div></div><Card title="Path analysis"><div className="empty-state"><div className="empty-orbit">↗</div><strong>No attack path has been calculated yet</strong><p>Once Cypheris has enough connected asset and telemetry context, this surface can explain how multiple findings combine into a higher-impact path.</p><Link className="secondary-button" to="/workspace/integrations">Connect environment</Link></div></Card></Shell>}
