import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useParams } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
const nav = [
  ["Overview", "/workspace"], ["Security", "/workspace/security"], ["Alerts", "/workspace/alerts"],
  ["Investigations", "/workspace/investigations"], ["Assets", "/workspace/assets"], ["Identity", "/workspace/identity"],
  ["Network", "/workspace/network"], ["Risk Graph", "/workspace/risk-graph"], ["Attack Paths", "/workspace/attack-paths"],
  ["Threat Intel", "/workspace/intelligence"], ["Drift", "/workspace/drift"], ["Timeline", "/workspace/timeline"],
  ["Evidence", "/workspace/evidence"], ["LYROMI", "/workspace/lyromi"], ["Sensors", "/workspace/sensors"],
  ["Integrations", "/workspace/integrations"], ["Reports", "/workspace/reports"], ["API", "/workspace/api"],
  ["Team", "/workspace/team"], ["Billing", "/workspace/billing"], ["Settings", "/workspace/settings"],
];
function headers(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
async function request(path, options={}){const r=await fetch(`${API}${path}`,{...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}
function Shell({children}){const location=useLocation(),navigate=useNavigate();const [collapsed,setCollapsed]=useState(false);const user=JSON.parse(localStorage.getItem("cypheris_user")||"null");const company=JSON.parse(localStorage.getItem("cypheris_company")||"null");useEffect(()=>{if(!localStorage.getItem("cypheris_access_token"))navigate("/login",{replace:true})},[navigate]);return <div className={`platform-shell ${collapsed?"sidebar-collapsed":""}`}><aside className="platform-sidebar"><Link className="platform-brand" to="/"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">SECURITY OPERATIONS</div><nav>{nav.map(([label,path])=><Link key={path} to={path} className={location.pathname===path?"active":""}><span className="nav-glyph">{label[0]}</span><span>{label}</span></Link>)}</nav><button className="collapse-button" onClick={()=>setCollapsed(!collapsed)}>{collapsed?">":"<"} Collapse</button></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Evidence-aware environment</span><div className="topbar-actions"><span>{company?.name||"Organization"}</span><span className="avatar">{(user?.name||"C")[0]}</span><button onClick={()=>{localStorage.clear();navigate("/login")}}>Sign out</button></div></header><main className="platform-content">{children}</main></section></div>}
function Page({eyebrow,title,description,children,action}){return <Shell><div className="page-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<div className="page-actions">{action}</div>}</div>{children}</Shell>}
function Card({title,meta,children}){return <section className="data-card"><div className="card-head"><span>{title}</span>{meta&&<small>{meta}</small>}</div>{children}</section>}
function Table({columns,rows,empty="No evidence yet. Connect a source or record an observation."}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{String(v??"—")}</td>)}</tr>):<tr><td className="empty" colSpan={columns.length}>{empty}</td></tr>}</tbody></table></div>}
function Metric({label,value,detail}){return <section className="data-card"><div className="card-head"><span>{label}</span><small>{detail}</small></div><strong className="card-value">{value}</strong></section>}
function fmt(v){return v?new Date(v).toLocaleString():"—"}

export function ContextOverview(){const [s,setS]=useState(null);useEffect(()=>{request("/api/context/summary").then(x=>setS(x.summary)).catch(()=>{})},[]);return <Page eyebrow="CYPHERIS / CONTEXT FABRIC" title="Evidence before conclusions" description="Cypheris connects telemetry, identity, assets, investigations and change history into one security context layer."><div className="metric-grid"><Metric label="Assets" value={s?.assets??"—"} detail="Observed inventory"/><Metric label="Identities" value={s?.identities??"—"} detail="Identity events"/><Metric label="Investigations" value={s?.investigations??"—"} detail="Response cases"/><Metric label="Evidence" value={s?.evidence??"—"} detail="Collected records"/><Metric label="Drift" value={s?.drift??"—"} detail="Detected changes"/></div><div className="two-column"><Card title="The Cypheris loop"><div className="pipeline"><span>01 Collect telemetry</span><span>02 Normalize evidence</span><span>03 Connect entities</span><span>04 Prioritize paths</span><span>05 Investigate</span><span>06 Explain with LYROMI</span><span>07 Respond and verify</span></div></Card><Card title="No silent assumptions"><p className="muted-copy">Unknown relationships stay unknown. Attack paths and AI analysis should be grounded in observed evidence, configured integrations or explicit operator input.</p></Card></div></Page>}

export function Investigations(){const [items,setItems]=useState([]),[title,setTitle]=useState(""),[summary,setSummary]=useState(""),[priority,setPriority]=useState("HIGH"),[msg,setMsg]=useState("");const load=()=>request("/api/context/investigations").then(x=>setItems(x.investigations||[])).catch(e=>setMsg(e.message));useEffect(load,[]);const create=async()=>{if(!title.trim())return;try{await request("/api/context/investigations",{method:"POST",body:JSON.stringify({title,summary,priority})});setTitle("");setSummary("");setMsg("Investigation opened.");load()}catch(e){setMsg(e.message)}};return <Page eyebrow="RESPONSE / INVESTIGATIONS" title="Investigation workspace" description="Turn a security signal into a traceable case with ownership, evidence and an auditable timeline." action={<button className="primary-button" onClick={create}>Open investigation</button>}><Card title="New investigation"><div className="form-grid"><input placeholder="Investigation title" value={title} onChange={e=>setTitle(e.target.value)}/><select value={priority} onChange={e=>setPriority(e.target.value)}><option>CRITICAL</option><option>HIGH</option><option>MEDIUM</option><option>LOW</option></select><input placeholder="Initial analyst summary" value={summary} onChange={e=>setSummary(e.target.value)}/><button className="primary-button" onClick={create}>Create case</button></div>{msg&&<p className="notice">{msg}</p>}</Card><Card title="Active and historical investigations"><Table columns={["Case","Status","Priority","Evidence","Events","Updated"]} rows={items.map(x=>[<Link to={`/workspace/investigations/${x.id}`}>{x.title}</Link>,x.status,x.priority,x.evidence_count,x.event_count,fmt(x.updated_at)])}/></Card></Page>}

export function InvestigationDetail(){const {id}=useParams();const [d,setD]=useState(null),[message,setMessage]=useState("");const load=()=>request(`/api/context/investigations/${id}`).then(setD).catch(e=>setMessage(e.message));useEffect(load,[id]);const addEvent=async()=>{if(!message.trim())return;try{await request(`/api/context/investigations/${id}/events`,{method:"POST",body:JSON.stringify({event_type:"analyst_note",message})});setMessage("");load()}catch(e){setMessage(e.message)}};return <Page eyebrow={`INVESTIGATION / ${id}`} title={d?.investigation?.title||"Investigation"} description={d?.investigation?.summary||"A traceable security investigation."} action={<Link className="secondary-button" to="/workspace/investigations">Back to investigations</Link>}><div className="metric-grid"><Metric label="Status" value={d?.investigation?.status||"—"} detail="Lifecycle"/><Metric label="Priority" value={d?.investigation?.priority||"—"} detail="Current"/><Metric label="Evidence" value={d?.evidence?.length??0} detail="Collected"/><Metric label="Events" value={d?.events?.length??0} detail="Timeline"/></div><div className="two-column"><Card title="Investigation timeline"><Table columns={["Type","Message","Time"]} rows={(d?.events||[]).map(x=>[x.event_type,x.message,fmt(x.created_at)])}/><div className="chat-input"><input placeholder="Add analyst note or decision..." value={message} onChange={e=>setMessage(e.target.value)}/><button className="primary-button" onClick={addEvent}>Record</button></div></Card><Card title="Evidence chain"><Table columns={["Type","Source","Subject","Observed"]} rows={(d?.evidence||[]).map(x=>[x.evidence_type,x.source,x.subject_key,fmt(x.observed_at)])}/></Card></div></Page>}

export function Assets(){const [items,setItems]=useState([]);useEffect(()=>{request("/api/context/assets").then(x=>setItems(x.assets||[])).catch(()=>{})},[]);const summary=useMemo(()=>({critical:items.filter(x=>x.criticality==="CRITICAL").length,external:items.filter(x=>x.exposure==="EXTERNAL").length,active:items.length}),[items]);return <Page eyebrow="SECURITY / ASSETS" title="Living asset inventory" description="A normalized inventory becomes the foundation for graph context, ownership and blast-radius reasoning."><div className="metric-grid"><Metric label="Observed assets" value={summary.active} detail="Current records"/><Metric label="Critical" value={summary.critical} detail="Business priority"/><Metric label="Externally exposed" value={summary.external} detail="Exposure signal"/></div><Card title="Asset inventory"><Table columns={["Asset","Type","Environment","Criticality","Exposure","Source","Last seen"]} rows={items.map(x=>[x.asset_name,x.asset_type,x.environment_name,x.criticality,x.exposure,x.source,fmt(x.last_seen)])}/></Card></Page>}

export function Identity(){const [items,setItems]=useState([]);useEffect(()=>{request("/api/context/identities").then(x=>setItems(x.identities||[])).catch(()=>{})},[]);return <Page eyebrow="IDENTITY / CONTEXT" title="Identity center" description="Identity activity is modeled as evidence that can influence investigations, risk and attack paths."><div className="metric-grid"><Metric label="Identity events" value={items.length} detail="Observed"/><Metric label="High risk" value={items.filter(x=>x.risk_score>=75).length} detail="Risk ≥ 75"/><Metric label="Medium risk" value={items.filter(x=>x.risk_score>=40&&x.risk_score<75).length} detail="Risk 40–74"/></div><Card title="Recent identity activity"><Table columns={["Identity","Event","Risk","Source","Observed"]} rows={items.map(x=>[x.identity_key,x.event_type,x.risk_score,x.source,fmt(x.observed_at)])}/></Card></Page>}

export function Drift(){const [items,setItems]=useState([]);useEffect(()=>{request("/api/context/drift").then(x=>setItems(x.events||[])).catch(()=>{})},[]);return <Page eyebrow="SECURITY / CHANGE" title="Security drift" description="Answer the question security teams repeatedly need: what changed, when, and what security context did it alter?"><Card title="Detected changes"><Table columns={["Subject","Change","Severity","Source","Detected"]} rows={items.map(x=>[x.subject_key,x.change_type,x.severity,x.source,fmt(x.detected_at)])}/></Card><Card title="How drift becomes intelligence"><div className="pipeline"><span>Baseline</span><span>Detect change</span><span>Compare before / after</span><span>Re-score risk</span><span>Recompute affected paths</span><span>Notify / investigate</span></div></Card></Page>}

export function Timeline(){const [items,setItems]=useState([]);useEffect(()=>{request("/api/context/timeline").then(x=>setItems(x.events||[])).catch(()=>{})},[]);return <Page eyebrow="SECURITY / TIMELINE" title="Security timeline" description="One chronological stream for alerts, identity activity, investigations, assets and security drift."><Card title="Chronology"><Table columns={["Time","Event","Severity","Subject","Source","Message"]} rows={items.map(x=>[fmt(x.occurred_at),x.event_type,x.severity,x.subject_key,x.source,x.message])}/></Card></Page>}

export function Evidence(){const [s,setS]=useState(null);useEffect(()=>{request("/api/context/summary").then(x=>setS(x.summary)).catch(()=>{})},[]);return <Page eyebrow="SECURITY / EVIDENCE" title="Evidence fabric" description="Cypheris keeps conclusions tied to the records that produced them instead of treating every signal as equally trustworthy."><div className="metric-grid"><Metric label="Evidence records" value={s?.evidence??"—"} detail="Collected"/><Metric label="Timeline records" value={s?.timeline??"—"} detail="Chronology"/><Metric label="Open alerts" value={s?.open_alerts??"—"} detail="Unresolved"/></div><Card title="Evidence principles"><div className="pipeline"><span>Observed ≠ inferred</span><span>Source is retained</span><span>Tenant scope is enforced</span><span>Unknown is explicit</span><span>Investigations preserve context</span></div></Card></Page>}
