import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
function headers(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
async function get(path){const r=await fetch(`${API}${path}`,{headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}
function Shell({children}){return <div className="platform-shell"><aside className="platform-sidebar"><Link className="platform-brand" to="/workspace"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">RESPONSE &amp; PLATFORM</div><nav><Link to="/workspace">Overview</Link><Link to="/workspace/security">Security</Link><Link to="/workspace/alerts">Alerts</Link><Link to="/workspace/incidents">Incidents</Link><Link to="/workspace/network">Network</Link><Link to="/workspace/assets">Assets</Link><Link to="/workspace/intelligence">Intelligence</Link><Link to="/workspace/risk-graph">Risk Graph</Link><Link to="/workspace/attack-paths">Attack Paths</Link><Link to="/workspace/reports">Reports</Link><Link to="/workspace/lyromi">LYROMI</Link><Link to="/workspace/integrations">Integrations</Link><Link to="/workspace/api">API</Link></nav></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Environment online</span><Link to="/workspace">Command center</Link></header><main className="platform-content">{children}</main></section></div>}
function Card({title,meta,children}){return <section className="data-card">{title&&<div className="card-head"><span>{title}</span>{meta&&<small>{meta}</small>}</div>}{children}</section>}
function Empty({title,body}){return <div className="empty-state"><div className="empty-orbit">CY</div><strong>{title}</strong><p>{body}</p></div>}
function Badge({value}){const k=String(value||"INFO").toLowerCase();return <span className={`risk-badge risk-${k}`}>{value||"INFO"}</span>}

export function Incidents(){const [data,setData]=useState(null);const [error,setError]=useState("");useEffect(()=>{get("/api/monitoring/alerts").then(setData).catch(e=>setError(e.message))},[]);const alerts=data?.alerts||[];const open=alerts.filter(x=>String(x.status||"").toLowerCase()==="open");return <Shell><div className="page-heading"><div><span>RESPONSE / INCIDENTS</span><h1>Incident workspace</h1><p>Turn evidence-backed detections into an investigation queue. This first response layer groups active findings without inventing incidents that do not exist.</p></div><Link className="secondary-button" to="/workspace/attack-paths">View attack paths</Link></div>{error&&<div className="notice">{error}</div>}<div className="metric-grid"><Card title="Open investigations">{open.length}</Card><Card title="Critical findings">{data?.summary?.critical??0}</Card><Card title="High findings">{data?.summary?.high??0}</Card><Card title="Evidence records">{alerts.length}</Card></div><div className="two-column"><Card title="Response queue" meta="Derived from current detections">{open.length?<div className="priority-list">{open.slice(0,12).map(a=><Link className="priority-row priority-link" to="/workspace/alerts" key={a.id}><div><strong>{a.alert_type||"Security finding"}</strong><small>{a.description||"No description provided."}</small></div><Badge value={a.severity}/><span>Investigate →</span></Link>)}</div>:<Empty title="No active incidents" body="When connected telemetry produces open detections, they will appear here for investigation."/>}</Card><Card title="Investigation lifecycle"><div className="pipeline"><span>01 Detect</span><span>02 Triage</span><span>03 Correlate</span><span>04 Contain</span><span>05 Resolve</span></div><p>Future response actions will stay linked to the original evidence, owner and audit trail.</p></Card></div></Shell>}

export function Reports(){const [dash,setDash]=useState(null),[alerts,setAlerts]=useState(null),[risk,setRisk]=useState(null),[error,setError]=useState("");useEffect(()=>{Promise.all([get("/api/dashboard/"),get("/api/monitoring/alerts"),get("/api/risk/context")]).then(([d,a,r])=>{setDash(d);setAlerts(a);setRisk(r)}).catch(e=>setError(e.message))},[]);const m=dash?.metrics||{},s=alerts?.summary||{},e=risk?.evidence||{};return <Shell><div className="page-heading"><div><span>REPORTING / POSTURE</span><h1>Security reports</h1><p>Executive-ready posture summaries assembled from the same tenant-scoped evidence used by the command center and risk graph.</p></div><button className="secondary-button" onClick={()=>window.print()}>Print / Save PDF</button></div>{error&&<div className="notice">{error}</div>}<Card title="Executive posture" meta="Current workspace evidence"><div className="report-hero"><div><span>Security score</span><strong>{m.security_score??"--"}</strong></div><div><span>Open alerts</span><strong>{s.open??0}</strong></div><div><span>Connected sources</span><strong>{(e.sensors||0)+(e.integrations||0)}</strong></div><div><span>Network observations</span><strong>{e.network_flows??0}</strong></div></div></Card><div className="two-column"><Card title="Risk summary"><div className="mini-list"><span>Critical <b>{s.critical??0}</b></span><span>High <b>{s.high??0}</b></span><span>Medium <b>{s.medium??0}</b></span><span>Low <b>{s.low??0}</b></span></div></Card><Card title="Evidence coverage"><div className="mini-list"><span>Sensors <b>{e.sensors??0}</b></span><span>Integrations <b>{e.integrations??0}</b></span><span>Identities <b>{e.identities??0}</b></span><span>Findings <b>{e.findings??0}</b></span><span>Network flows <b>{e.network_flows??0}</b></span></div></Card></div><Card title="Report integrity"><p>This report does not fabricate security activity. Empty sections mean the workspace has not supplied enough evidence yet. As integrations mature, the same report can expand into compliance, incident timelines, remediation ownership and scheduled delivery.</p></Card></Shell>}

export function Api(){const groups=[{name:"Authentication",items:["POST /api/login","POST /api/signup"]},{name:"Workspace",items:["GET /api/dashboard/","GET /api/workspace/company","GET /api/workspace/team","GET /api/workspace/audit"]},{name:"Security data",items:["GET /api/monitoring/alerts","GET /api/monitoring/network","GET /api/monitoring/assets","GET /api/monitoring/notifications"]},{name:"Risk intelligence",items:["GET /api/risk/context","GET /api/risk/priorities","GET /api/risk/attack-paths","POST /api/lyromi/chat"]},{name:"Integrations & billing",items:["GET /api/integrations","POST /api/integrations/cloud","GET /api/billing/plans","GET /api/billing/subscription"]}];return <Shell><div className="page-heading"><div><span>DEVELOPER PLATFORM</span><h1>Cypheris API</h1><p>A structured entry point for integrations, automation and future customer applications. Authentication and tenant scoping remain enforced by the backend.</p></div><Link className="secondary-button" to="/workspace/integrations">Manage integrations</Link></div><Card title="API surface" meta="Current platform contract"><div className="api-groups">{groups.map(g=><section className="api-group" key={g.name}><div><strong>{g.name}</strong><small>{g.items.length} endpoints</small></div>{g.items.map(item=><code key={item}>{item}</code>)}</section>)}</div></Card><div className="two-column"><Card title="Integration model"><p>Use organization-scoped credentials and connected environments rather than exposing database access. Future API keys, scopes, rate limits and webhook subscriptions belong here.</p></Card><Card title="Developer roadmap"><div className="pipeline"><span>01 API keys</span><span>02 Scopes</span><span>03 Webhooks</span><span>04 Rate limits</span></div></Card></div></Shell>}
