import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
function headers(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
async function get(path){const r=await fetch(`${API}${path}`,{headers:headers()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}
function Shell({children}){return <div className="platform-shell"><aside className="platform-sidebar"><Link className="platform-brand" to="/workspace"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">RESPONSE</div><nav><Link to="/workspace">Overview</Link><Link to="/workspace/security">Security</Link><Link to="/workspace/alerts">Alerts</Link><Link to="/workspace/incidents" className="active">Incidents</Link><Link to="/workspace/risk-graph">Risk Graph</Link><Link to="/workspace/reports">Reports</Link></nav></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Response workspace</span><Link to="/workspace">Back to command center</Link></header><main className="platform-content">{children}</main></section></div>}
function Card({title,meta,children}){return <section className="data-card"><div className="card-head"><span>{title}</span>{meta&&<small>{meta}</small>}</div>{children}</section>}
function Empty(){return <div className="empty-state"><div className="empty-orbit">IR</div><strong>No incidents require response</strong><p>Cypheris does not invent incidents. When connected alerts and telemetry establish an investigation, this workspace will organize the evidence here.</p><Link className="secondary-button" to="/workspace/alerts">Open Alert Center</Link></div>}
export default function Incidents(){const [d,setD]=useState(null);const [error,setError]=useState("");useEffect(()=>{get("/api/monitoring/alerts").then(setD).catch(e=>setError(e.message))},[]);const alerts=d?.alerts||[];const open=alerts.filter(x=>String(x.status||"").toLowerCase()==="open");return <Shell><div className="page-heading"><div><span>RESPONSE / INVESTIGATION</span><h1>Incident workspace</h1><p>Turn correlated security findings into an investigation surface with evidence, ownership and response context.</p></div><Link className="secondary-button" to="/workspace/alerts">Review detections</Link></div>{error&&<div className="notice">{error}</div>}<div className="metric-grid"><Card title="Open findings">{open.length}</Card><Card title="Critical">{alerts.filter(x=>String(x.severity||"").toLowerCase()==="critical").length}</Card><Card title="High">{alerts.filter(x=>String(x.severity||"").toLowerCase()==="high").length}</Card><Card title="Evidence records">{alerts.length}</Card></div><Card title="Active investigations" meta="Derived from current evidence">{open.length?<div className="table-wrap"><table><thead><tr><th>Finding</th><th>Severity</th><th>Status</th><th>Created</th><th>Next surface</th></tr></thead><tbody>{open.slice(0,50).map(a=><tr key={a.id}><td>{a.alert_type}</td><td>{a.severity}</td><td>{a.status}</td><td>{a.created_at||"—"}</td><td><Link to="/workspace/risk-graph">Investigate graph →</Link></td></tr>)}</tbody></table></div>:<Empty/>}</Card><div className="two-column"><Card title="Investigation flow"><div className="pipeline"><span>01 Detection</span><span>02 Correlate evidence</span><span>03 Assess blast radius</span><span>04 Assign response</span><span>05 Verify closure</span></div></Card><Card title="Response principle"><p>Every investigation should be traceable to evidence. Cypheris connects alerts to the context graph and risk queue instead of creating a separate silo.</p></Card></div></Shell>}
