import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
function headers(){const token=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(token?{Authorization:`Bearer ${token}`}:{})};}
async function get(path){const response=await fetch(`${API}${path}`,{headers:headers()});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.detail||"Request failed");return data;}
function Shell({children}){return <div className="platform-shell"><aside className="platform-sidebar"><Link className="platform-brand" to="/workspace"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">COMMAND CENTER</div><nav><Link to="/workspace">Overview</Link><Link to="/workspace/security">Security</Link><Link to="/workspace/alerts">Alerts</Link><Link to="/workspace/network">Network</Link><Link to="/workspace/assets">Assets</Link><Link to="/workspace/intelligence">Intelligence</Link><Link to="/workspace/notifications">Notifications</Link></nav></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Live security data</span><Link to="/workspace">Back to command center</Link></header><main className="platform-content">{children}</main></section></div>}
function Card({title,meta,children}){return <section className="data-card">{title&&<div className="card-head"><span>{title}</span>{meta&&<small>{meta}</small>}</div>}{children}</section>}
function Badge({value}){const key=String(value||"INFO").toLowerCase();return <span className={`risk-badge risk-${key}`}>{value||"INFO"}</span>}
function Empty({title,body}){return <div className="empty-state"><div className="empty-orbit">CY</div><strong>{title}</strong><p>{body}</p></div>}

export function Alerts(){const [data,setData]=useState(null);const [error,setError]=useState("");useEffect(()=>{get("/api/monitoring/alerts").then(setData).catch(e=>setError(e.message))},[]);const s=data?.summary||{};return <Shell><div className="page-heading"><div><span>SECURITY / DETECTION</span><h1>Alert center</h1><p>Review workspace findings with severity and lifecycle context. Cypheris shows the records it actually has.</p></div><Link className="secondary-button" to="/workspace/attack-paths">Open risk queue</Link></div>{error&&<div className="notice">{error}</div>}<div className="metric-grid"><Card title="Open">{s.open??0}</Card><Card title="Critical">{s.critical??0}</Card><Card title="High">{s.high??0}</Card><Card title="Total">{s.total??0}</Card></div><Card title="Detections" meta="Latest 200"><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Finding</th><th>Description</th><th>Status</th><th>Created</th></tr></thead><tbody>{(data?.alerts||[]).length?(data.alerts.map(a=><tr key={a.id}><td><Badge value={a.severity}/></td><td>{a.alert_type}</td><td>{a.description||"No description provided."}</td><td>{a.status}</td><td>{a.created_at||"—"}</td></tr>)):<tr><td className="empty" colSpan="5">No detections are currently recorded.</td></tr>}</tbody></table></div></Card></Shell>}

export function Network(){const [data,setData]=useState(null);const [error,setError]=useState("");useEffect(()=>{get("/api/monitoring/network").then(setData).catch(e=>setError(e.message))},[]);const s=data?.summary||{};return <Shell><div className="page-heading"><div><span>SECURITY / NETWORK</span><h1>Network intelligence</h1><p>Observe communication patterns from telemetry connected to this workspace without manufacturing topology.</p></div></div>{error&&<div className="notice">{error}</div>}<div className="metric-grid"><Card title="Flows">{s.flows??0}</Card><Card title="Sources">{s.unique_sources??0}</Card><Card title="Destinations">{s.unique_destinations??0}</Card><Card title="Bytes">{Number(s.bytes||0).toLocaleString()}</Card></div><div className="two-column"><Card title="Protocol mix"><div className="mini-list">{Object.entries(s.protocols||{}).map(([name,count])=><span key={name}>{name}<b>{count}</b></span>)}</div></Card><Card title="Most observed sources"><div className="mini-list">{(s.top_sources||[]).map(item=><span key={item.address}>{item.address}<b>{item.observations}</b></span>)}{!s.top_sources?.length&&<span>No source telemetry yet.</span>}</div></Card></div><Card title="Recent flows"><div className="table-wrap"><table><thead><tr><th>Source</th><th>Destination</th><th>Protocol</th><th>Packets</th><th>Bytes</th><th>Observed</th></tr></thead><tbody>{(data?.flows||[]).length?data.flows.slice(0,100).map((f,i)=><tr key={`${f.detected_at}-${i}`}><td>{f.source_ip||"—"}</td><td>{f.destination_ip||"—"}</td><td>{f.protocol||"—"}</td><td>{Number(f.packets||0).toLocaleString()}</td><td>{Number(f.bytes||0).toLocaleString()}</td><td>{f.detected_at||"—"}</td></tr>):<tr><td className="empty" colSpan="6">No network telemetry is available yet.</td></tr>}</tbody></table></div></Card></Shell>}

export function Assets(){const [data,setData]=useState(null);const [error,setError]=useState("");useEffect(()=>{get("/api/monitoring/assets").then(setData).catch(e=>setError(e.message))},[]);const s=data?.summary||{};return <Shell><div className="page-heading"><div><span>SECURITY / ASSETS</span><h1>Asset inventory</h1><p>A living view of sensors and connected security environments known to the workspace.</p></div><Link className="secondary-button" to="/workspace/integrations">Connect source</Link></div>{error&&<div className="notice">{error}</div>}<div className="metric-grid"><Card title="Known assets">{s.total??0}</Card><Card title="Sensors">{s.sensors??0}</Card><Card title="Integrations">{s.integrations??0}</Card><Card title="Active">{s.active??0}</Card></div><Card title="Connected asset inventory"><div className="table-wrap"><table><thead><tr><th>Source</th><th>Name</th><th>Environment</th><th>Type</th><th>Status</th><th>Heartbeat</th></tr></thead><tbody>{(data?.assets||[]).length?data.assets.map(item=><tr key={`${item.source}-${item.id}`}><td>{item.source}</td><td>{item.name}</td><td>{item.environment_name}</td><td>{item.environment_type}</td><td>{item.status}</td><td>{item.last_heartbeat||"No heartbeat"}</td></tr>):<tr><td className="empty" colSpan="6">No connected assets yet. Start with a sensor or integration.</td></tr>}</tbody></table></div></Card></Shell>}

export function Intelligence(){return <Shell><div className="page-heading"><div><span>INTELLIGENCE</span><h1>Threat intelligence</h1><p>Contextual intelligence is built from the evidence entering Cypheris. External enrichment can be connected here as integrations mature.</p></div></div><div className="two-column"><Card title="Current intelligence sources"><Empty title="Awaiting connected intelligence" body="Cypheris will keep this surface evidence-backed. Connect telemetry and intelligence integrations before drawing conclusions about external threats."/></Card><Card title="Investigation workflow"><div className="pipeline"><span>01 Collect signal</span><span>02 Correlate context</span><span>03 Prioritize risk</span><span>04 Investigate</span></div></Card></div><Card title="Next layer"><p>Threat intelligence will feed the existing risk graph, priority queue and LYROMI context rather than becoming a disconnected feed reader.</p></Card></Shell>}

export function Notifications(){const [data,setData]=useState(null);useEffect(()=>{get("/api/monitoring/notifications").then(setData).catch(()=>{})},[]);return <Shell><div className="page-heading"><div><span>COMMUNICATIONS</span><h1>Notifications</h1><p>Security and organization events that require attention.</p></div></div><Card title="Notification stream" meta={`${data?.unread??0} unread`}><div className="notification-list">{(data?.notifications||[]).length?data.notifications.map(n=><article className="notification-item" key={n.id}><div><strong>{n.title||"Cypheris notification"}</strong><p>{n.message||"No additional message."}</p></div><small>{n.created_at||"Recent"}</small></article>):<Empty title="You're caught up" body="No notifications are currently recorded for this workspace."/>}</div></Card></Shell>}
