import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
const nav = [["Overview","/workspace"],["Command","/workspace/overview"],["Context","/workspace/context"],["Security","/workspace/security"],["Alerts","/workspace/alerts"],["Investigations","/workspace/investigations"],["Network","/workspace/network"],["Assets","/workspace/assets"],["Identity","/workspace/identity"],["Risk Graph","/workspace/risk-graph"],["Attack Paths","/workspace/attack-paths"],["Drift","/workspace/drift"],["Timeline","/workspace/timeline"],["Evidence","/workspace/evidence"],["LYROMI","/workspace/lyromi"],["Integrations","/workspace/integrations"],["Reports","/workspace/reports"],["Team","/workspace/team"],["Billing","/workspace/billing"],["Settings","/workspace/settings"],["Audit","/workspace/audit"],["API","/workspace/api"]];

export function authHeaders(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
export async function request(path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}

export function Shell({children}){const location=useLocation(),navigate=useNavigate();const user=JSON.parse(localStorage.getItem("cypheris_user")||"null");const company=JSON.parse(localStorage.getItem("cypheris_company")||"null");const [collapsed,setCollapsed]=useState(false);useEffect(()=>{if(!localStorage.getItem("cypheris_access_token"))navigate("/login",{replace:true})},[navigate]);const logout=()=>{["cypheris_access_token","cypheris_token_type","cypheris_user","cypheris_company"].forEach(k=>localStorage.removeItem(k));navigate("/login")};return <div className={`platform-shell ${collapsed?"sidebar-collapsed":""}`}><aside className="platform-sidebar"><Link className="platform-brand" to="/"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>{company?.name||"Security Fabric"}</small></span></Link><div className="workspace-label">COMMAND CENTER</div><nav>{nav.map(([label,path])=><Link key={path} to={path} className={location.pathname===path?"active":""}><span className="nav-glyph">{label[0]}</span><span>{label}</span></Link>)}</nav><button className="collapse-button" onClick={()=>setCollapsed(!collapsed)}>{collapsed?">":"<"} Collapse</button></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Workspace</span><div className="topbar-actions"><span>{company?.name||"Organization"}</span><span className="avatar">{(user?.name||"C")[0]}</span><button onClick={logout}>Sign out</button></div></header><main className="platform-content">{children}</main></section></div>}
export function Page({eyebrow,title,description,children,action}){return <Shell><div className="page-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<div className="page-actions">{action}</div>}</div>{children}</Shell>}
export function Card({title,meta,children}){return <section className="data-card">{title&&<div className="card-head"><span>{title}</span>{meta&&<small>{meta}</small>}</div>}{children}</section>}
export function Table({columns,rows}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{String(v??"—")}</td>)}</tr>):<tr><td className="empty" colSpan={columns.length}>No records yet.</td></tr>}</tbody></table></div>}
