import { useEffect, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import "./PlatformPages.css";

const API = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";
const nav = [["Overview","/workspace"],["Context","/workspace/context"],["Security","/workspace/security"],["Alerts","/workspace/alerts"],["Investigations","/workspace/investigations"],["Network","/workspace/network"],["Assets","/workspace/assets"],["Identity","/workspace/identity"],["Sensors","/workspace/sensors"],["Intelligence","/workspace/intelligence"],["Risk Graph","/workspace/risk-graph"],["Attack Paths","/workspace/attack-paths"],["Drift","/workspace/drift"],["Timeline","/workspace/timeline"],["Evidence","/workspace/evidence"],["LYROMI","/workspace/lyromi"],["Reports","/workspace/reports"],["Integrations","/workspace/integrations"],["Notifications","/workspace/notifications"],["Team","/workspace/team"],["Billing","/workspace/billing"],["Settings","/workspace/settings"],["Audit","/workspace/audit"],["API","/workspace/api"]];

function authHeaders(){const t=localStorage.getItem("cypheris_access_token");return {"Content-Type":"application/json",...(t?{Authorization:`Bearer ${t}`}:{})};}
async function request(path, options={}){const r=await fetch(`${API}${path}`,{...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||"Request failed");return d;}

function Shell({children}){const location=useLocation(),navigate=useNavigate();const user=JSON.parse(localStorage.getItem("cypheris_user")||"null");const company=JSON.parse(localStorage.getItem("cypheris_company")||"null");const [collapsed,setCollapsed]=useState(false);useEffect(()=>{if(!localStorage.getItem("cypheris_access_token"))navigate("/login",{replace:true});},[navigate]);const logout=()=>{["cypheris_access_token","cypheris_token_type","cypheris_user","cypheris_company"].forEach(k=>localStorage.removeItem(k));navigate("/login")};return <div className={`platform-shell ${collapsed?"sidebar-collapsed":""}`}><aside className="platform-sidebar"><Link className="platform-brand" to="/"><span className="brand-mark">CY</span><span><strong>Cypheris</strong><small>Security Fabric</small></span></Link><div className="workspace-label">COMMAND CENTER</div><nav>{nav.map(([label,path])=><Link key={path} to={path} className={location.pathname===path?"active":""}><span className="nav-glyph">{label[0]}</span><span>{label}</span></Link>)}</nav><button className="collapse-button" onClick={()=>setCollapsed(!collapsed)}>{collapsed?">":"<"} Collapse</button></aside><section className="platform-main"><header className="platform-topbar"><span><i className="live-dot"/>Environment online</span><div className="topbar-actions"><span>{company?.name||"Organization"}</span><span className="avatar">{(user?.name||"C")[0]}</span><button onClick={logout}>Sign out</button></div></header><main className="platform-content">{children}</main></section></div>}

function Page({eyebrow,title,description,children,action}){return <Shell><div className="page-heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{action&&<div className="page-actions">{action}</div>}</div>{children}</Shell>}
function Card({title,meta,children}){return <section className="data-card">{title&&<div className="card-head"><span>{title}</span>{meta&&<small>{meta}</small>}</div>}{children}</section>}
function Empty({title,body,link}){return <div className="empty-state"><div className="empty-orbit">CY</div><strong>{title}</strong><p>{body}</p>{link&&<Link className="secondary-button" to={link[0]}>{link[1]}</Link>}</div>}

export function Overview(){const [d,setD]=useState(null);useEffect(()=>{request("/api/dashboard/").then(setD).catch(()=>{})},[]);const m=d?.metrics||{};return <Page eyebrow="CYPHERIS / OVERVIEW" title="Security command center" description="A unified operating view for posture, telemetry, detections and connected environments." action={<Link className="primary-button" to="/workspace/integrations">Connect environment</Link>}><div className="metric-grid"><Metric title="Security score" value={m.security_score??"--"} meta="Current posture"/><Metric title="Active alerts" value={m.active_alerts??"--"} meta="Requires attention"/><Metric title="Online sensors" value={m.online_sensors??"--"} meta="Live sources"/><Metric title="Telemetry" value={m.telemetry_total??"--"} meta="Observed signals"/></div><div className="two-column"><Card title="Threat posture" meta="Live"><div className="posture"><div className="posture-ring">{m.security_score??"--"}</div><div><strong>{d?.threat_level||"Monitoring"}</strong><p>Cypheris correlates the signals entering your environment and surfaces what needs investigation.</p></div></div></Card><Card title="Integration fabric" meta="Connected sources"><div className="mini-list"><span>Cloud <b>{m.cloud_integrations??0}</b></span><span>API <b>{m.api_integrations??0}</b></span><span>Online <b>{m.online_integrations??0}</b></span></div></Card></div><Card title="Recent activity"><Table columns={["Event","Severity","Time"]} rows={(d?.activity||[]).slice(0,8).map(x=>[x.description||x.action||"Security event",x.severity||"INFO",x.created_at||"Recent"])}/></Card></Page>}
function Metric({title,value,meta}){return <Card title={title} meta={meta}><strong className="card-value">{value}</strong></Card>}
function Table({columns,rows}){return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{String(v??"—")}</td>)}</tr>):<tr><td className="empty" colSpan={columns.length}>No records yet. Connect a source to populate this view.</td></tr>}</tbody></table></div>}

const copy={Security:["SECURITY / POSTURE","Security posture","See the controls and findings shaping your organization's current security state."],Alerts:["SECURITY / ALERTS","Alert center","Investigate detections, prioritize risk and move findings toward resolution."],Network:["SECURITY / NETWORK","Network intelligence","Explore communication patterns, protocols and unusual network behavior."],Assets:["SECURITY / ASSETS","Asset inventory","Build a living inventory of infrastructure connected to the security fabric."],Sensors:["SECURITY / SENSORS","Sensor fleet","Enroll and monitor the sensors providing visibility into your environments."],Intelligence:["INTELLIGENCE","Threat intelligence","Correlate security observations with context and prioritized intelligence."],Incidents:["RESPONSE","Incident workspace","Organize investigations, ownership, evidence and response progress."],Reports:["REPORTING","Security reports","Create executive and operational security reports from workspace data."],Notifications:["COMMUNICATIONS","Notifications","Review security and organization notifications in one place."],API:["DEVELOPER PLATFORM","API access","Connect Cypheris to internal systems through controlled developer interfaces."]};
export function Simple({name}){const [e,t,d]=copy[name];return <Page eyebrow={e} title={t} description={d} action={<button className="secondary-button">Export</button>}><Card title={t}><Empty title={`${t} is ready`} body="This surface is connected to the Cypheris workspace model. Live records appear here as telemetry, integrations and response data enter the platform." link={["/workspace/integrations","Connect a source"]}/></Card><div className="metric-grid"><Metric title="Monitored" value="--" meta="Live data"/><Metric title="Open" value="--" meta="Requires action"/><Metric title="Resolved" value="--" meta="Historical"/><Metric title="Coverage" value="--" meta="Environment"/></div></Page>}

export function Sensors(){return <Page eyebrow="SECURITY / SENSORS" title="Sensor fleet" description="Enroll sensors and monitor the health of the devices feeding PNSTAP telemetry." action={<Link className="primary-button" to="/install-sensor">Enroll sensor</Link>}><Card title="Sensor fleet"><Empty title="Connect your first sensor" body="Sensor enrollment is organization-scoped and uses a device credential separate from human authentication." link={["/install-sensor","Start enrollment"]}/></Card></Page>}

export function Integrations(){const [items,setItems]=useState([]);const [form,setForm]=useState({connection_name:"",environment_name:"",provider:"aws"});const [msg,setMsg]=useState("");const load=()=>request("/api/integrations").then(x=>setItems(x.integrations||[])).catch(()=>{});useEffect(load,[]);const create=async()=>{try{const x=await request("/api/integrations/cloud",{method:"POST",body:JSON.stringify({...form,environment_type:"infrastructure"})});setMsg(x.message||"Connection created");setForm({connection_name:"",environment_name:"",provider:"aws"});load()}catch(e){setMsg(e.message)}};return <Page eyebrow="CONNECTIVITY" title="Integrations" description="Connect cloud, SIEM, EDR and custom security sources into the Cypheris fabric."><Card title="New cloud connection"><div className="form-grid"><input placeholder="Connection name" value={form.connection_name} onChange={e=>setForm({...form,connection_name:e.target.value})}/><input placeholder="Environment name" value={form.environment_name} onChange={e=>setForm({...form,environment_name:e.target.value})}/><select value={form.provider} onChange={e=>setForm({...form,provider:e.target.value})}><option value="aws">AWS</option><option value="azure">Azure</option><option value="gcp">Google Cloud</option></select><button className="primary-button" onClick={create}>Create connection</button></div>{msg&&<p className="notice">{msg}</p>}</Card><Card title="Connected sources"><Table columns={["Connection","Environment","Type","Provider","Status"]} rows={items.map(x=>[x.connection_name,x.environment_name,x.integration_type,x.provider||x.api_platform||"—",x.status])}/></Card></Page>}

export function Lyromi(){const [q,setQ]=useState(""),[r,setR]=useState("LYROMI is ready for a security question."),[busy,setBusy]=useState(false);const ask=async()=>{if(!q.trim())return;setBusy(true);setR("");try{const response=await fetch(`${API}/api/lyromi/stream`,{method:"POST",headers:authHeaders(),body:JSON.stringify({message:q.trim()})});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).detail||"LYROMI request failed");if(!response.body)throw new Error("Streaming is not available in this browser.");const reader=response.body.getReader();const decoder=new TextDecoder();let text="";while(true){const {value,done}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true});setR(text)}}catch(e){setR(e.message)}finally{setBusy(false)}};return <Page eyebrow="AI SECURITY INTELLIGENCE" title="LYROMI" description="Interpret security signals with the Cypheris intelligence layer, with token streaming so the first answer appears as soon as the local model produces it."><div className="lyromi-grid"><Card title="LYROMI / ANALYSIS"><div className="chat-response">{r||<span className="muted">LYROMI is thinking…</span>}</div><div className="chat-input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder="Ask about an alert, signal or environment..."/><button className="primary-button" disabled={busy} onClick={ask}>{busy?"Analyzing…":"Ask LYROMI"}</button></div></Card><Card title="Analysis flow"><div className="pipeline"><span>01 Signal ingestion</span><span>02 Context correlation</span><span>03 LYROMI reasoning</span><span>04 Human decision</span></div><p className="notice">Local inference stays configurable through Ollama environment settings. Keep the model warm to reduce cold-start latency.</p></Card></div></Page>}

export function Billing(){const [sub,setSub]=useState(null),[plans,setPlans]=useState(null),[msg,setMsg]=useState("");useEffect(()=>{request("/api/billing/subscription").then(x=>setSub(x.subscription)).catch(()=>{});request("/api/billing/plans").then(setPlans).catch(()=>{})},[]);const choose=async plan=>{try{const x=await request("/api/billing/select-plan",{method:"POST",body:JSON.stringify({plan,billing_cycle:"Yearly",payment_provider:plan==="Enterprise"?"bank_transfer":"stripe"})});setSub(x.subscription);setMsg(x.message);if(plan!=="Free"&&plan!=="Enterprise"){try{const checkout=await request("/api/billing/checkout",{method:"POST"});if(checkout.checkout_url)window.location.href=checkout.checkout_url}catch(e){setMsg(`${x.message} ${e.message}`)}}}catch(e){setMsg(e.message)}};return <Page eyebrow="ACCOUNT / BILLING" title="Plans & billing" description="Seven days of full-access trial, followed by yearly subscription activation for continued access."><Card title="Current subscription"><div className="subscription-banner"><strong>{sub?.plan||"Free"}</strong><span>{sub?.status||"Loading"}</span><b>{sub?.trial_active?`${sub.trial_days_remaining} trial days remaining`:sub?.annual_price?`$${sub.annual_price.toLocaleString()}/year`:"$0"}</b></div>{msg&&<p className="notice">{msg}</p>}</Card><div className="pricing-grid">{plans&&Object.entries(plans.plans).map(([name,p])=><article className="pricing-card" key={name}><span>{name}</span><strong>${p.annual_price.toLocaleString()}</strong><small>/ year</small><p>{name==="Free"?"1 user · 7-day retention":`${p.user_limit>=1000000?"Unlimited":p.user_limit+" users"} · ${p.retention_days}-day retention`}</p><button className="primary-button" onClick={()=>choose(name)}>{name==="Enterprise"?"Select Enterprise":"Choose "+name}</button></article>)}</div><p className="billing-note">Over-limit users: $10/user/month. Planned payment rails: Stripe and PayPal; Enterprise supports bank transfer. Payment provider secrets and webhook verification belong in deployment configuration.</p></Page>}

export function Settings(){const [company,setCompany]=useState(null),[primary,setPrimary]=useState("#00E5FF"),[secondary,setSecondary]=useState("#0A1628"),[msg,setMsg]=useState("");useEffect(()=>{request("/api/workspace/company").then(x=>{setCompany(x.company);setPrimary(x.company.brand_primary_color||"#00E5FF");setSecondary(x.company.brand_secondary_color||"#0A1628")}).catch(()=>{})},[]);const save=async()=>{try{const x=await request("/api/workspace/company/branding",{method:"PUT",body:JSON.stringify({primary_color:primary,secondary_color:secondary,logo_url:company?.logo_url||null})});setCompany({...company,...x.company});setMsg("Branding saved.")}catch(e){setMsg(e.message)}};return <Page eyebrow="ADMINISTRATION" title="Workspace settings" description="Configure organization identity and the visual language of your security workspace."><Card title="Organization identity"><div className="branding-preview"><div className="brand-preview-mark" style={{background:primary}}>CY</div><div><strong>{company?.company_name||"Organization"}</strong><p>Workspace identity</p></div></div><div className="form-grid"><label>Primary color<input type="color" value={primary} onChange={e=>setPrimary(e.target.value)}/></label><label>Secondary color<input type="color" value={secondary} onChange={e=>setSecondary(e.target.value)}/></label><button className="primary-button" onClick={save}>Save branding</button></div>{msg&&<p className="notice">{msg}</p>}</Card></Page>}

export function Team(){const [members,setMembers]=useState([]);useEffect(()=>{request("/api/workspace/team").then(x=>setMembers(x.members||[])).catch(()=>{})},[]);return <Page eyebrow="ADMINISTRATION" title="Team access" description="Review members in this organization and their current role/status."><Card title="Organization members"><Table columns={["Name","Email","Role","Status","Last login"]} rows={members.map(x=>[x.full_name,x.email,x.role,x.status,x.last_login||"Never"])}/></Card></Page>}
export function Audit(){const [events,setEvents]=useState([]);useEffect(()=>{request("/api/workspace/audit").then(x=>setEvents(x.events||[])).catch(()=>{})},[]);return <Page eyebrow="GOVERNANCE" title="Audit trail" description="A tenant-scoped record of security-sensitive organization activity."><Card title="Recent audit events"><Table columns={["Action","User","IP","Time"]} rows={events.map(x=>[x.action||"—",x.user_id||"—",x.ip_address||"—",x.created_at||"—"])}/></Card></Page>}